apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-server
  labels:
    app: nginx-server

# ==========================================
# 1. DEPLOYMENT CONFIGURATION
# ==========================================
spec:
  replicas: 4

  selector:
    matchLabels:
      app: nginx-server



  # ==========================================
  # 2. POD TEMPLATE CONFIGURATION
  # ==========================================
  template:
    metadata:
      labels:
        app: nginx-server

    spec:
      containers:
        - name: nginx-server
          image: nginx:alpine 

          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL123
              value: "https://rds.ap-south-1a.amazon.com"
            - name: DATABASE_USERNAME123
              value: admin
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: database_url
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: database_username
            - name: S3_URL
              valueFrom:
                configMapKeyRef:
                  name: commons-configmap
                  key: s3_url
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: db_password
               


        